name: Deployment
on: push
jobs:
  lint:
      - name: getcode
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
      - name: dependencies
      - name: lint
        run : npm run lint
  test:
      - name: getcode
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
      - name: dependencies
        run: npm ci
      - name: test
        run : npm run test
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: getcode
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
      - name: dependencies
        run : npm ci
     
      - name: Build code
        run : npm run build
      - name: Deploy code
        run : echo "deploying...."
    